# This script is for variables that we are accessing from inventory file.
# In inventory we can create group and host variables.
- name: variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"
      