
- name: install nginx
  hosts: dynamic_frontend
  become: yes
  serial: 5 # serial means it will took first 5 instances after completion again take 5 
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes


